### ISSUE TITLE
6. Cómo simbolizarlas

### ISSUE THREAD

**Issue by oscarfonts** [geoinquiets/taller-vt#12]
* [x] A máquina (maputnik)
* [x] A mano (json + documentación)

**Comment by bolollo** [comment]
Podemos usar el mbtiles de natural earth de https://github.com/lukasmartinelli/naturalearthtiles/releases/tag/v1.0

**Comment by rroset** [comment]
+1

**Comment by bolollo** [comment]
He creado una rama llamada estilos para ir trabajando este tema. Ya que voy a instalar el maputnik en mi máquina, así aprovecho y voy documentando el proceso de Instalación.

**Comment by bolollo** [comment]
Creo que aquí solo faltaría la parte del estilo 3D de los edificios pero esto lo podemos poner en la parte de servir datos dinámicos del punto 6. Así que esta issue se podría cerrar

**Comment by oscarfonts** [comment]
Haré una prueba a ver si los edificios 3D van más o menos rápidos servidos dinámicamente, pero me temo que los tendremos que servir también estáticos (el dato es complejo...).
