### ISSUE TITLE
6. Cómo servir datos dinámicos

### ISSUE THREAD

**Issue by oscarfonts** [geoinquiets/taller-vt#13]
* [x] Crear capa en PostGIS
* [x] Servir con servidor postgis => pbf (tegola)
* [x] Añadir overlay dinámico al servidor

**Comment by rroset** [comment]
Tegola però també TRex o directament amb https://postgis.net/docs/ST_AsMVT.html

**Comment by oscarfonts** [comment]
Al final t-rex fa tanta màgia que peta.
Tornant a tegola.
