### ISSUE TITLE
4. Cómo crearlas

### ISSUE THREAD

**Issue by bolollo** [geoinquiets/taller-vt#2]
Convertir datos de GeoJSON a mbtiles vectoriales con tippecanoe

**Comment by oscarfonts** [comment]
Sobre la instalación de Tippecanoe en Ubuntu,
recuerdo haber hecho un make / make install y poco más.

En este apartado dice qué dependencias hacen falta: https://github.com/mapbox/tippecanoe#development

**Comment by bolollo** [comment]
Para los datos usaría los de Natural Earth, lo ideal sería montar más de una capa.  Aquí están los geojson https://github.com/nvkelso/natural-earth-vector/tree/master/geojson.

**Comment by rroset** [comment]
+1
