### ISSUE TITLE
cd ruta-relativa

### ISSUE THREAD

**Issue by fergonco** [geoinquiets/taller-vt#30]
los 'cd' a rutas relativas pueden crear confusión. 

En el punto 3 hay un 'cd tileserver' pero yo ya estaba ahí.

**Comment by fergonco** [comment]
Bueno, no es sólo para los 'cd'. Para cualquier comando que tenga rutas también aplica (mkdir, etc.).

**Comment by oscarfonts** [comment]
Se ha intentado subsanar en https://github.com/geoinquiets/taller-vt/commit/3b1bfd2cf01cf29bdfcc13fa49e4adea8be21ceb esperems que con acierto
