### ISSUE TITLE
Proposta d'iteracions

### ISSUE THREAD

**Issue by oscarfonts** [geoinquiets/taller-vt#4]
0. Presentació dels tutors i del taller. La teoria de VT.
1. Muntar un visor ràpid: Agafar algun servei que ja existeixi (openmaptiles), amb un estil que ja existeixi (ídem), i muntar un visor chorra. Afegir-hi mapbox-gl-inspect (útil per veure com són les dades per dintre).
2. Muntar un servidor de mapes: Agafar un mbtiles que ja existeixi (openmaptiles) i servir-lo nosaltres en localhost (tileserver-gl, o altre més lleuger que conegueu).
3. Generar dades estàtiques pròpies: tippecanoe.
4. Simbolitzar dades pròpies amb maputnik.
5. Servidor de tiles dinàmic (tegola?) -- segurament implicarà carregar dades a PostGIS.

**Comment by bolollo** [comment]
El punto 1. está hecho en la rama de visor simple. Se podría agregar algo de explicar un poco el estilo que se carga o lo podemos dejar para el punto 2.
